In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\intel\Desktop\Internship\Bondora_raw\Bondora_raw.csv",low_memory=False)

In [3]:
df.head()

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,PreviousEarlyRepaymentsCountBeforeLoan,GracePeriodStart,GracePeriodEnd,NextPaymentDate,NextPaymentNr,NrOfScheduledPayments,ReScheduledOn,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost,ActiveLateLastPaymentCategory
0,2020-01-27,F0660C80-83F3-4A97-8DA0-9C250112D6EC,659,2009-06-11 16:40:39,2009-06-11 16:40:39,0,0,115.0410,KARU,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1,2020-01-27,978BB85B-1C69-4D51-8447-9C240104A3A2,654,2009-06-10 15:48:57,2009-06-10 15:48:57,0,0,140.6057,koort681,False,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
2,2020-01-27,EA44027E-7FA7-4BB2-846D-9C1F013C8A22,641,2009-06-05 19:12:29,2009-06-05 19:12:29,0,0,319.5580,0ie,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,180+
3,2020-01-27,CE67AD25-2951-4BEE-96BD-9C2700C61EF4,668,2009-06-13 12:01:20,2009-06-13 12:01:20,0,0,57.5205,Alyona,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
4,2020-01-27,9408BF8C-B159-4D6A-9D61-9C2400A986E3,652,2009-06-10 10:17:13,2009-06-10 10:17:13,0,0,319.5582,Kai,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,180+

# Task 1 - Data Preprocessing and Preparation

In [4]:
# no. of features in dataset
df.shape

(134529, 112)

In [5]:
df.columns

Index(['ReportAsOfEOD', 'LoanId', 'LoanNumber', 'ListedOnUTC',
       'BiddingStartedOn', 'BidsPortfolioManager', 'BidsApi', 'BidsManual',
       'UserName', 'NewCreditCustomer',
       ...
       'PreviousEarlyRepaymentsCountBeforeLoan', 'GracePeriodStart',
       'GracePeriodEnd', 'NextPaymentDate', 'NextPaymentNr',
       'NrOfScheduledPayments', 'ReScheduledOn', 'PrincipalDebtServicingCost',
       'InterestAndPenaltyDebtServicingCost', 'ActiveLateLastPaymentCategory'],
      dtype='object', length=112)

In [6]:
# List attributes presnet in dataset 
for i in df.columns:
    print(i)

ReportAsOfEOD
LoanId
LoanNumber
ListedOnUTC
BiddingStartedOn
BidsPortfolioManager
BidsApi
BidsManual
UserName
NewCreditCustomer
LoanApplicationStartedDate
LoanDate
ContractEndDate
FirstPaymentDate
MaturityDate_Original
MaturityDate_Last
ApplicationSignedHour
ApplicationSignedWeekday
VerificationType
LanguageCode
Age
DateOfBirth
Gender
Country
AppliedAmount
Amount
Interest
LoanDuration
MonthlyPayment
County
City
UseOfLoan
Education
MaritalStatus
NrOfDependants
EmploymentStatus
EmploymentDurationCurrentEmployer
EmploymentPosition
WorkExperience
OccupationArea
HomeOwnershipType
IncomeFromPrincipalEmployer
IncomeFromPension
IncomeFromFamilyAllowance
IncomeFromSocialWelfare
IncomeFromLeavePay
IncomeFromChildSupport
IncomeOther
IncomeTotal
ExistingLiabilities
LiabilitiesTotal
RefinanceLiabilities
DebtToIncome
FreeCash
MonthlyPaymentDay
ActiveScheduleFirstPaymentReached
PlannedPrincipalTillDate
PlannedInterestTillDate
LastPaymentOn
CurrentDebtDaysPrimary
DebtOccuredOn
CurrentDebtDaysSecondary
DebtOccuredOnForSecondary
ExpectedLoss
LossGivenDefault
ExpectedReturn
ProbabilityOfDefault
DefaultDate
PrincipalOverdueBySchedule
PlannedPrincipalPostDefault
PlannedInterestPostDefault
EAD1
EAD2
PrincipalRecovery
InterestRecovery
RecoveryStage
StageActiveSince
ModelVersion
Rating
EL_V0
Rating_V0
EL_V1
Rating_V1
Rating_V2
Status
Restructured
ActiveLateCategory
WorseLateCategory
CreditScoreEsMicroL
CreditScoreEsEquifaxRisk
CreditScoreFiAsiakasTietoRiskGrade
CreditScoreEeMini
PrincipalPaymentsMade
InterestAndPenaltyPaymentsMade
PrincipalWriteOffs
InterestAndPenaltyWriteOffs
PrincipalBalance
InterestAndPenaltyBalance
NoOfPreviousLoansBeforeLoan
AmountOfPreviousLoansBeforeLoan
PreviousRepaymentsBeforeLoan
PreviousEarlyRepaymentsBefoleLoan
PreviousEarlyRepaymentsCountBeforeLoan
GracePeriodStart
GracePeriodEnd
NextPaymentDate
NextPaymentNr
NrOfScheduledPayments
ReScheduledOn
PrincipalDebtServicingCost
InterestAndPenaltyDebtServicingCost
ActiveLateLastPaymentCategory

In [7]:
# Checking Null value
df.isnull().sum()

ReportAsOfEOD                              0
LoanId                                     0
LoanNumber                                 0
ListedOnUTC                                0
BiddingStartedOn                           0
                                       ...
NrOfScheduledPayments                  36741
ReScheduledOn                          94207
PrincipalDebtServicingCost             75400
InterestAndPenaltyDebtServicingCost    75400
ActiveLateLastPaymentCategory          82279
Length: 112, dtype: int64

In [8]:
list_of_drop_columns = []
for i in df.columns:
    if df[i].isnull().sum() >= 100000:
        list_of_drop_columns.append(i)

In [9]:
list_of_drop_columns

['EL_V0',
 'Rating_V0',
 'EL_V1',
 'Rating_V1',
 'Rating_V2',
 'CreditScoreEsEquifaxRisk',
 'CreditScoreFiAsiakasTietoRiskGrade',
 'GracePeriodStart',
 'GracePeriodEnd']

In [10]:
# Droping the columns which have more than or equal to  100000 null values
df.drop(list_of_drop_columns, axis = 1, inplace = True)

In [11]:
# Selecting only Important  features
df= df[['Age','Amount','AmountOfPreviousLoansBeforeLoan','AppliedAmount',
          'City','ContractEndDate','Country','County','CreditScoreEeMini',
          'CreditScoreEsMicroL', 'CurrentDebtDaysPrimary',
          'CurrentDebtDaysPrimary','CurrentDebtDaysSecondary',
          'DebtOccuredOn','DebtOccuredOnForSecondary','DebtToIncome','DefaultDate',
          'Education','EmploymentDurationCurrentEmployer','EmploymentStatus',
          'ExistingLiabilities','ExpectedReturn','ExpectedLoss','Gender','HomeOwnershipType',
          'IncomeTotal','Interest','InterestAndPenaltyBalance','InterestAndPenaltyPaymentsMade',
          'InterestAndPenaltyWriteOffs','LanguageCode','LiabilitiesTotal',
          'LoanDate','LoanDuration','LoanId','LoanNumber','LossGivenDefault','MaritalStatus',
          'ModelVersion','MonthlyPayment','NoOfPreviousLoansBeforeLoan','NrOfScheduledPayments','OccupationArea',
          'PlannedInterestPostDefault','PlannedPrincipalPostDefault', 'PreviousRepaymentsBeforeLoan',
          'PrincipalBalance','PrincipalDebtServicingCost',
          'PrincipalPaymentsMade','PrincipalRecovery','PrincipalWriteOffs','ProbabilityOfDefault',
          'RecoveryStage','RefinanceLiabilities',
          'Status','UseOfLoan','UserName','VerificationType','WorseLateCategory' ]]

In [12]:
df.head()

,Age,Amount,AmountOfPreviousLoansBeforeLoan,AppliedAmount,City,ContractEndDate,Country,County,CreditScoreEeMini,CreditScoreEsMicroL,...,PrincipalRecovery,PrincipalWriteOffs,ProbabilityOfDefault,RecoveryStage,RefinanceLiabilities,Status,UseOfLoan,UserName,VerificationType,WorseLateCategory
0,61,115.0408,83.0852,319.5582,TALLINN,2010-07-06,EE,HARJU,NaN,NaN,...,NaN,0.0,NaN,NaN,0,Repaid,7,KARU,2.0,91-120
1,48,140.6057,255.6467,191.7349,KOHTLA-JARVE,2009-07-07,EE,IDA-VIRU,NaN,NaN,...,NaN,0.0,NaN,NaN,0,Repaid,7,koort681,2.0,NaN
2,58,319.5409,0.0000,319.5582,PÃ„RNU,NaN,EE,PÃ„RNU,NaN,NaN,...,163.1549,0.0,NaN,NaN,0,Late,2,0ie,2.0,180+
3,23,57.5205,134.2144,127.8233,PALDISKI,2010-09-15,EE,HARJU,NaN,NaN,...,NaN,0.0,NaN,NaN,0,Repaid,0,Alyona,2.0,31-60
4,25,319.5436,146.9966,319.5582,TARTU,2016-07-28,EE,TARTU,NaN,NaN,...,319.5436,0.0,NaN,NaN,0,Repaid,6,Kai,2.0,180+

In [13]:
df.dtypes

Age                                    int64
Amount                               float64
AmountOfPreviousLoansBeforeLoan      float64
AppliedAmount                        float64
City                                  object
ContractEndDate                       object
Country                               object
County                                object
CreditScoreEeMini                    float64
CreditScoreEsMicroL                   object
CurrentDebtDaysPrimary               float64
CurrentDebtDaysPrimary               float64
CurrentDebtDaysSecondary             float64
DebtOccuredOn                         object
DebtOccuredOnForSecondary             object
DebtToIncome                         float64
DefaultDate                           object
Education                            float64
EmploymentDurationCurrentEmployer     object
EmploymentStatus                     float64
ExistingLiabilities                    int64
ExpectedReturn                       float64
ExpectedLoss                         float64
Gender                               float64
HomeOwnershipType                    float64
IncomeTotal                          float64
Interest                             float64
InterestAndPenaltyBalance            float64
InterestAndPenaltyPaymentsMade       float64
InterestAndPenaltyWriteOffs          float64
LanguageCode                           int64
LiabilitiesTotal                     float64
LoanDate                              object
LoanDuration                           int64
LoanId                                object
LoanNumber                             int64
LossGivenDefault                     float64
MaritalStatus                        float64
ModelVersion                         float64
MonthlyPayment                       float64
NoOfPreviousLoansBeforeLoan            int64
NrOfScheduledPayments                float64
OccupationArea                       float64
PlannedInterestPostDefault           float64
PlannedPrincipalPostDefault          float64
PreviousRepaymentsBeforeLoan         float64
PrincipalBalance                     float64
PrincipalDebtServicingCost           float64
PrincipalPaymentsMade                float64
PrincipalRecovery                    float64
PrincipalWriteOffs                   float64
ProbabilityOfDefault                 float64
RecoveryStage                        float64
RefinanceLiabilities                   int64
Status                                object
UseOfLoan                              int64
UserName                              object
VerificationType                     float64
WorseLateCategory                     object
dtype: object

In [14]:
print(df.shape)

(134529, 59)

In [15]:
# Target Variable
df['Status'].value_counts()

Current    57135
Late       45772
Repaid     31622
Name: Status, dtype: int64

In [16]:
# New dataframe excluding 'Current' status
df = df[df['Status'] != 'Current']

In [17]:
df['Status'].value_counts()

Late      45772
Repaid    31622
Name: Status, dtype: int64

# Coversion of Target variable into Binary 0 or 1

In [18]:
# Converting Target variable into Binary ie. 0 or 1 
df['Status'].replace(['Late','Repaid'],[0,1],inplace = True)

In [19]:
df['Status']

0         1
1         1
2         0
3         1
4         1
         ..
134524    1
134525    1
134526    0
134527    1
134528    0
Name: Status, Length: 77394, dtype: int64

In [20]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Age,77394.0,39.611611,12.188868,0.000000,30.000000,38.000000,48.000000,7.700000e+01
Amount,77394.0,2472.673771,2163.710046,6.390000,740.000000,2020.000000,3185.000000,1.063200e+04
AmountOfPreviousLoansBeforeLoan,77394.0,2172.676382,3889.556046,0.000000,0.000000,0.000000,3000.000000,5.110400e+04
AppliedAmount,77394.0,2746.981169,2463.487043,31.955800,740.000000,2125.000000,3720.000000,1.063200e+04
CreditScoreEeMini,34364.0,944.811431,110.284370,0.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
CurrentDebtDaysPrimary,48518.0,593.448019,569.495276,2.000000,115.000000,415.000000,914.000000,3.919000e+03
CurrentDebtDaysPrimary,48518.0,593.448019,569.495276,2.000000,115.000000,415.000000,914.000000,3.919000e+03
CurrentDebtDaysSecondary,49757.0,641.708885,608.603322,2.000000,139.000000,459.000000,986.000000,3.938000e+03
DebtToIncome,77349.0,12.011918,18.829522,0.000000,0.000000,0.000000,20.810000,1.980200e+02
Education,77349.0,3.704961,1.138152,-1.000000,3.000000,4.000000,5.000000,5.000000e+00
EmploymentStatus,77197.0,0.819553,2.171963,-1.000000,-1.000000,-1.000000,3.000000,6.000000e+00
ExistingLiabilities,77394.0,3.350815,3.494328,0.000000,1.000000,2.000000,5.000000,3.600000e+01
ExpectedReturn,74760.0,0.145960,0.094625,-0.798891,0.113640,0.143027,0.187807,8.085465e-01
ExpectedLoss,74760.0,0.178596,0.138144,0.000000,0.079978,0.145579,0.242647,1.008540e+00
Gender,77349.0,0.418583,0.625625,0.000000,0.000000,0.000000,1.000000,2.000000e+00
HomeOwnershipType,75742.0,3.370046,2.717713,-1.000000,1.000000,3.000000,4.000000,1.000000e+01
IncomeTotal,77394.0,1868.974610,6193.487209,0.000000,890.000000,1300.000000,2000.000000,1.012019e+06
Interest,77394.0,40.301650,30.617950,3.000000,23.420000,31.955000,50.330000,2.643100e+02
InterestAndPenaltyBalance,77394.0,1215.017495,3220.010093,-2.660000,0.000000,84.805000,1083.985000,6.449477e+04
InterestAndPenaltyPaymentsMade,77394.0,502.770026,829.168708,0.000000,37.450000,191.165000,612.415000,1.450724e+04
InterestAndPenaltyWriteOffs,50409.0,101.838988,845.428542,0.000000,0.000000,0.000000,0.000000,4.435219e+04
LanguageCode,77394.0,3.056529,2.016316,1.000000,1.000000,3.000000,4.000000,2.200000e+01
LiabilitiesTotal,77394.0,714.925531,44591.417286,0.000000,113.040000,383.000000,736.000000,1.240000e+07
LoanDuration,77394.0,44.425498,16.412387,1.000000,36.000000,48.000000,60.000000,6.000000e+01
LoanNumber,77394.0,717126.257733,403271.294446,37.000000,439233.250000,701936.500000,978763.250000,1.846199e+06
LossGivenDefault,74760.0,0.550223,0.266511,0.000000,0.459668,0.599315,0.681751,9.501652e-01
MaritalStatus,77349.0,0.410878,1.762825,-1.000000,-1.000000,-1.000000,2.000000,5.000000e+00
ModelVersion,74760.0,4.000174,2.105464,0.000000,2.000000,5.000000,6.000000,6.000000e+00
MonthlyPayment,70767.0,130.393314,131.480383,0.000000,37.975000,101.130000,175.475000,2.368540e+03
NoOfPreviousLoansBeforeLoan,77394.0,1.140799,2.028045,0.000000,0.000000,0.000000,1.000000,2.400000e+01
NrOfScheduledPayments,40666.0,51.556362,11.197909,3.000000,36.000000,60.000000,60.000000,7.200000e+01
OccupationArea,77308.0,2.753247,5.678410,-1.000000,-1.000000,-1.000000,6.000000,1.900000e+01
PlannedInterestPostDefault,42794.0,1100.319453,1515.735227,0.000000,152.865000,594.280000,1485.057500,3.835299e+04
PlannedPrincipalPostDefault,42794.0,849.579869,1271.235840,0.000000,88.295000,323.030000,1103.635000,1.056781e+04
PreviousRepaymentsBeforeLoan,58078.0,861.138387,2076.791326,0.000000,0.000000,40.815000,653.740000,3.407742e+04
PrincipalBalance,77394.0,1372.262893,1944.295361,-34.200000,0.000000,516.865000,2111.980000,1.063200e+04
PrincipalDebtServicingCost,50409.0,6.174838,62.555772,0.000000,0.000000,0.000000,0.000000,3.325330e+03
PrincipalPaymentsMade,77394.0,1077.613937,1648.865768,0.000000,61.690000,462.810000,1451.292500,1.063200e+04
PrincipalRecovery,42794.0,335.076727,825.664924,0.000000,0.000000,0.000000,259.230000,1.062999e+04
PrincipalWriteOffs,50409.0,28.825786,263.855605,0.000000,0.000000,0.000000,0.000000,1.062999e+04
ProbabilityOfDefault,74760.0,0.280921,0.162856,0.000000,0.149186,0.269451,0.394706,9.852907e-01
RecoveryStage,50503.0,1.723462,0.447290,1.000000,1.000000,2.000000,2.000000,2.000000e+00
RefinanceLiabilities,77394.0,0.300127,1.123265,0.000000,0.000000,0.000000,0.000000,2.300000e+01
Status,77394.0,0.408585,0.491575,0.000000,0.000000,0.000000,1.000000,1.000000e+00
UseOfLoan,77394.0,1.130979,4.049870,-1.000000,-1.000000,-1.000000,2.000000,1.100000e+02
VerificationType,77349.0,2.849061,1.364773,0.000000,1.000000,4.000000,4.000000,4.000000e+00

In [21]:
df.head()

,Age,Amount,AmountOfPreviousLoansBeforeLoan,AppliedAmount,City,ContractEndDate,Country,County,CreditScoreEeMini,CreditScoreEsMicroL,...,PrincipalRecovery,PrincipalWriteOffs,ProbabilityOfDefault,RecoveryStage,RefinanceLiabilities,Status,UseOfLoan,UserName,VerificationType,WorseLateCategory
0,61,115.0408,83.0852,319.5582,TALLINN,2010-07-06,EE,HARJU,NaN,NaN,...,NaN,0.0,NaN,NaN,0,1,7,KARU,2.0,91-120
1,48,140.6057,255.6467,191.7349,KOHTLA-JARVE,2009-07-07,EE,IDA-VIRU,NaN,NaN,...,NaN,0.0,NaN,NaN,0,1,7,koort681,2.0,NaN
2,58,319.5409,0.0000,319.5582,PÃ„RNU,NaN,EE,PÃ„RNU,NaN,NaN,...,163.1549,0.0,NaN,NaN,0,0,2,0ie,2.0,180+
3,23,57.5205,134.2144,127.8233,PALDISKI,2010-09-15,EE,HARJU,NaN,NaN,...,NaN,0.0,NaN,NaN,0,1,0,Alyona,2.0,31-60
4,25,319.5436,146.9966,319.5582,TARTU,2016-07-28,EE,TARTU,NaN,NaN,...,319.5436,0.0,NaN,NaN,0,1,6,Kai,2.0,180+